allowBuilds:
  '@ffmpeg-installer/linux-x64': set this to true or false
  '@firebase/util': set this to true or false
  protobufjs: set this to true or false
  unrs-resolver: set this to true or false
